movies/src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("movies.urls")),  # Подключаем маршруты приложения movies
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/src/movies/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path("", views.MovieListView.as_view(), name="movie_list"),  # Список фильмов
    path(
        "movie/<int:pk>/", views.MovieDetailView.as_view(), name="movie_detail"
    ),  # Детальная страница фильма
    path("login/", views.CustomLoginView.as_view(), name="login"),  # Авторизация
    path("logout/", LogoutView.as_view(), name="logout"),
    path(
        "register/", views.CustomRegisterView.as_view(), name="register"
    ),  # Регистрация
    path("movie/<int:pk>/rate/", views.rate_movie, name="rate_movie"),
    path("movie/<int:pk>/review/", views.review_movie, name="review_movie"),
]

movies/src/movies/models.py
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth import get_user_model
from decimal import *
import math

User = get_user_model()


class Genre(models.Model):
    name = models.CharField(max_length=100, verbose_name="Жанр")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанр"
        ordering = ["name"]


class Director(models.Model):
    name = models.CharField(max_length=100, verbose_name="Режиссер")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Режиссер"
        verbose_name_plural = "Режиссеры"
        ordering = ["name"]


class Country(models.Model):
    name = models.CharField(max_length=100, verbose_name="Страна")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Страна"
        verbose_name_plural = "Страны"
        ordering = ["name"]


class Actor(models.Model):
    name = models.CharField(max_length=100, verbose_name="Актер")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Актер"
        verbose_name_plural = "Актеры"
        ordering = ["name"]


class MediaType(models.Model):
    name = models.CharField(max_length=50, verbose_name="Тип медиа")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тип медиа"
        verbose_name_plural = "Типы медиа"
        ordering = ["name"]


class Movie(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название фильма")
    description = models.TextField(verbose_name="Описание фильма")
    trailer = models.URLField(verbose_name="Ссылка на трейлер")
    year = models.IntegerField(verbose_name="Год выхода")

    countries = models.ManyToManyField(Country, verbose_name="Страны", blank=True)
    genres = models.ManyToManyField(Genre, verbose_name="Жанры", blank=True)
    directors = models.ManyToManyField(Director, verbose_name="Режиссер", blank=True)
    actors = models.ManyToManyField(Actor, verbose_name="Актеры", blank=True)

    image = models.ImageField(
        upload_to="movies/", verbose_name="Изображение", blank=True, null=True
    )

    # Поле для внешней ссылки на изображение
    external_image_url = models.URLField(
        blank=True, null=True, verbose_name="URL изображения"
    )

    # Связь с моделью MediaType
    media_type = models.ForeignKey(
        MediaType, on_delete=models.CASCADE, verbose_name="Тип медиа", null=True
    )

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"

    def clean(self):
        # Создадим валидатор для проверки URL
        validator = URLValidator()
        if self.external_image_url:
            try:
                validator(self.external_image_url)
            except ValidationError:
                raise ValidationError(
                    {"external_image_url": "Введённый URL недействителен."}
                )

    def get_image_url(self):
        """
        Возвращает URL для изображения: сначала пытается взять из поля `image`,
        затем из `external_image_url`. Если оба пустые — возвращает URL заглушки.
        """
        if self.image:
            return self.image.url
        elif self.external_image_url:
            return self.external_image_url
        return "/static/images/placeholder.png"  # Путь к изображению-заглушке

    def __str__(self):
        return self.title

    def average_rating(self):
        """Вычисляет средний рейтинг фильма"""
        ratings = self.ratings.all()
        if not ratings.exists():
            return None
        avg = sum(rating.value for rating in ratings) / ratings.count()
        return round(avg, 1)
        # return avg.quantize(Decimal("1.00"))
        # return math.ceil(avg)
        # return avg

    def rating_count(self):
        """Возвращает количество оценок для фильма"""
        return self.ratings.count()

    def review_count(self):
        """Возвращает количество рецензий для фильма"""
        return self.reviews.count()


class Rating(models.Model):
    RATING_CHOICES = [(i, str(i)) for i in range(1, 11)]  # Оценки от 1 до 10

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="ratings")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="ratings")
    value = models.IntegerField(choices=RATING_CHOICES, verbose_name="Рейтинг")

    class Meta:
        unique_together = ("user", "movie")
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинг"

    def __str__(self):
        return f"{self.user.username} - {self.movie.title}: {self.value}"


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reviews")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name="reviews")
    content = models.TextField(verbose_name="Рецензия")
    created_at = models.DateTimeField(auto_now_add=True)  # Устанавливается при создании
    updated_at = models.DateTimeField(
        auto_now=True
    )  # Обновляется при каждом сохранении

    class Meta:
        unique_together = ("user", "movie")
        verbose_name = "рецензия"
        verbose_name_plural = "рецензии"
        ordering = ["-created_at"]

    def __str__(self):
        media_type = (
            self.movie.media_type.name.lower()
            if self.movie.media_type
            else "unknown type"
        )
        return f"Рецензия '{self.user.username}' на {media_type} '{self.movie.title}'"

movies/src/movies/views.py
import logging

from django.db.models import Avg, Max
from django.db.models.functions import Round
from django.shortcuts import render

from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Movie, MediaType, Country, Genre, Rating, Review

# Настраиваем логгер для приложения "movies"
logger = logging.getLogger("movies")


class MovieListView(ListView):
    model = Movie
    template_name = "movies/movie_list.html"
    context_object_name = "movies"

    def get_queryset(self):
        queryset = Movie.objects.all()

        # Аннотация для среднего рейтинга
        # queryset = queryset.annotate(average_rating=Avg("ratings__value"))
        queryset = queryset.annotate(average_rating=Round(Avg("ratings__value"), 1))

        # Фильтры
        media = self.request.GET.get("media")
        country = self.request.GET.get("country")
        genre = self.request.GET.get("genre")
        year = self.request.GET.get("year")
        sort = self.request.GET.get(
            "sort", "title"
        )  # По умолчанию сортировка по названию

        if media:
            queryset = queryset.filter(media_type__id=media)
        if country:
            queryset = queryset.filter(countries__id=country)
        if genre:
            queryset = queryset.filter(genres__id=genre)
        if year:
            queryset = queryset.filter(year=year)

        # Сортировка
        if sort == "-average_rating":
            queryset = queryset.order_by("-average_rating")
        elif sort == "average_rating":
            queryset = queryset.order_by("average_rating")
        else:
            queryset = queryset.order_by(sort)

        return queryset.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Добавляем данные для фильтров
        context["media_types"] = MediaType.objects.all()
        context["countries"] = Country.objects.all()
        context["genres"] = Genre.objects.all()
        context["years"] = (
            Movie.objects.values_list("year", flat=True).distinct().order_by("-year")
        )

        return context


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movies/movie_detail.html"
    context_object_name = "movie"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Диапазон оценок от 1 до 10
        context["rating_range"] = range(1, 11)

        # Текущая оценка пользователя (если он авторизован)
        if self.request.user.is_authenticated:
            user_rating = Rating.objects.filter(
                movie=self.object, user=self.request.user
            ).first()
            context["user_rating"] = user_rating.value if user_rating else None

            # Текущая рецензия пользователя (если есть)
            user_review = Review.objects.filter(
                movie=self.object, user=self.request.user
            ).first()
            context["user_review"] = user_review
        else:
            context["user_rating"] = None
            context["user_review"] = None

        # Список рецензий
        context["reviews"] = Review.objects.filter(movie=self.object).order_by(
            "-updated_at"
        )

        return context


class CustomLoginView(LoginView):
    template_name = "movies/login.html"
    redirect_authenticated_user = True


class CustomRegisterView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = "movies/register.html"
    success_url = reverse_lazy("movie_list")

    def form_valid(self, form):
        # Автоматический вход после регистрации
        user = form.save()
        from django.contrib.auth import login

        login(self.request, user)
        return super().form_valid(form)


# def movie_detail(request, movie_id):
#     # Пример данных
#     movie = Movie.objects.get(pk=movie_id)
#     user_rating = 7  # Пример: оценка пользователя
#     user_review = None  # Пример: рецензия пользователя
#
#     context = {
#         "movie": movie,
#         "user_rating": user_rating,
#         "user_review": user_review,
#         "rating_range": range(1, 11),  # Диапазон оценок
#     }
#     return render(request, "movies/movie_detail.html", context)


@login_required
def rate_movie(request, pk):
    # Получаем фильм
    movie = get_object_or_404(Movie, pk=pk)

    if request.method == "POST":
        rating_value = request.POST.get("rating")
        if rating_value and rating_value.isdigit():
            rating_value = int(rating_value)
            if 1 <= rating_value <= 10:  # Проверяем, что оценка в диапазоне 1-10
                # Ищем существующий рейтинг для пользователя
                rating, created = Rating.objects.get_or_create(
                    movie=movie, user=request.user, defaults={"value": rating_value}
                )
                if not created:
                    rating.value = rating_value  # Обновляем оценку
                    rating.save()
                    logger.info(
                        "Пользователь с id %s успешно изменил рейтинг к фильму с id %s",
                        request.user.id,
                        movie.pk,
                    )

    return redirect("movie_detail", pk=movie.pk)


@login_required
def review_movie(request, pk):
    # Получаем фильм
    movie = get_object_or_404(Movie, pk=pk)

    if request.method == "POST":
        review_content = request.POST.get("review")
        if review_content:
            # Ищем существующую рецензию для пользователя
            review, created = Review.objects.get_or_create(
                movie=movie, user=request.user, defaults={"content": review_content}
            )
            if not created:
                review.content = review_content  # Обновляем рецензию
                review.save()
                logger.info(
                    "Пользователь с id %s успешно опубликовал рецензию на фильм с id %s",
                    request.user.id,
                    movie.pk,
                )

    return redirect("movie_detail", pk=movie.pk)

movies/src/templates/movies/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Login</h2>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>
{% endblock %}

movies/src/templates/movies/movie_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <!-- Левая часть: изображение -->
        <div class="col-md-4">
<!--            <img src="{{ movie.get_image_url }}" class="img-fluid rounded mx-auto d-block" alt="{{ movie.title }}">-->
            <div class="container">
                <img src="{{ movie.get_image_url }}" class="img-fluid rounded" alt="{{ movie.title }}">
            </div>


            <!-- Видео -->
<!--            {% if movie.trailer %}-->
<!--            <div class="mt-3">-->
<!--                <video controls class="w-100 rounded">-->
<!--                    <source src="{{ movie.trailer }}" type="video/mp4">-->
<!--                    Ваш браузер не поддерживает просмотр видео. <a href="{{ movie.trailer }}" target="_blank">Смотреть трейлер</a>.-->
<!--                </video>-->
<!--            </div>-->
<!--            {% endif %}-->


        </div>

        <!-- Правая часть: информация, рейтинг, рецензии -->
        <div class="col-md-8">
            <h2>{{ movie.title }}</h2>

            <h6 class="card-text text-muted mb-1 text-truncate">
                {{ movie.media_type.name }}
            </h6>

            <p>{{ movie.description }}</p>

            <ul class="list-unstyled">
                <li><strong>Год производства:</strong> {{ movie.year }}</li>
                <li><strong>Страны:</strong> {{ movie.countries.all|join:", " }}</li>
                <li><strong>Жанры:</strong> {{ movie.genres.all|join:", " }}</li>
                <li><strong>Режиссеры:</strong> {{ movie.directors.all|join:", " }}</li>
                <li><strong>Актеры:</strong> {{ movie.actors.all|join:", " }}</li>
            </ul>
            <div class="d-flex align-items-center mt-3">
                <i class="bi bi-star-fill text-warning me-2"></i>
                <span class="fs-5">{{ movie.average_rating|default:"0.0" }}</span>
                <span class="text-muted ms-2">({{ movie.rating_count|default:"0" }})</span>
            </div>

            <!-- Блок "Моя оценка" и "Написать рецензию" -->
            {% if user.is_authenticated %}
            {% include "movies/user_interaction.html" %}
            {% endif %}

            <!-- Список рецензий -->
            <div class="mt-4">
                <h5>Рецензии зрителей</h5>
                {% include "movies/review_list.html" %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

movies/src/templates/movies/movie_item.html
<div class="col-md-4 mb-4">
    <div class="card h-100 d-flex flex-column">

        <!-- Ссылка с изображением -->
        <a href="{% url 'movie_detail' movie.id %}" class="stretched-link">
            <img src="{{ movie.get_image_url }}" class="card-img-top" alt="{{ movie.title }}">
        </a>

        <div class="card-body d-flex flex-column">

            <h5 class="card-title text-truncate">{{ movie.title }} </h5>
            <div class="mt-auto">

                <!-- Год и страны -->
                <h6 class="card-text text-muted mb-1 text-truncate">
                    {{ movie.year }} · {{ movie.countries.all|join:", " }}
                </h6>

                <!-- Жанры -->
                <p class="card-text text-muted mb-1 text-truncate">
                    {{ movie.genres.all|join:", " }}
                </p>

                <!-- Актеры -->
                <p class="card-text text-muted text-truncate">
                    <small>В ролях:</small> {{ movie.actors.all|join:", " }}
                </p>

                <p class="card-text">{{ movie.description|truncatechars:85 }}</p>

            <!-- Рейтинг и кнопка -->

                <div class="d-flex justify-content-between align-items-center">

                    <div class="d-flex align-items-center">
                        <!-- Количество рецензий -->
                        <i class="bi bi-chat-square-text text-secondary me-1"></i>  <!-- Иконка чата -->
                        <span class="me-3">{{ movie.review_count|default:"0" }}</span>
                        <!-- Рейтинг -->
                        <i class="bi bi-star-fill text-warning me-2"></i>  <!-- Иконка звезды -->
                        <span class="fs-5">{{ movie.average_rating|default:"0.0" }}</span> <!-- Средний рейтинг -->
                        <span class="text-muted ms-2">({{ movie.rating_count|default:"0" }})</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

movies/src/templates/movies/movie_list.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <!-- Sidebar -->
    <div class="col-md-3">
        {% include "movies/sidebar.html" %}
    </div>

    <!-- Movie List -->
    <div class="col-md-9">
        <div class="row">
            {% for movie in movies %}
                {% include "movies/movie_item.html" %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

movies/src/templates/movies/register.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2>Register</h2>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
</div>
{% endblock %}

movies/src/templates/movies/review_list.html
{% for review in reviews %}
<div class="border rounded p-3 mb-3">

    <div class="d-flex justify-content-between align-items-center">
        <h6>{{ review.user.username }}</h6>
        <div class="d-flex align-items-center">
            <p class="text-muted small">{{ review.updated_at|date:"d M Y в H:i" }}</p>
        </div>
    </div>

    <p>{{ review.content }}</p>

</div>
{% empty %}
<p class="text-muted">Рецензий пока нет. Будьте первым, кто напишет рецензию!</p>
{% endfor %}

movies/src/templates/movies/sidebar.html
<script>
    function submitFilterForm() {
        document.getElementById('filter-form').submit();
    }
</script>

<aside class="bg-light p-3 rounded">
<!--    <h5>movies X select</h5>-->
<!--    <i class="bi bi-film"></i>-->
    <form method="GET" action="." id="filter-form">
        <!-- Фильтр по медиа -->
        <div class="mb-3">
            <label for="media" class="form-label">Медиа</label>
            <select class="form-select" name="media" id="media" onchange="submitFilterForm()">
                <option value="">Все медиа</option>
                {% for media in media_types %}
                    <option value="{{ media.id }}" {% if request.GET.media|default:'' == media.id|stringformat:"s" %}selected{% endif %}>
                        {{ media.name }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <!-- Фильтр по странам -->
        <div class="mb-3">
            <label for="country" class="form-label">Страна</label>
            <select class="form-select" name="country" id="country" onchange="submitFilterForm()">
                <option value="">Все страны</option>
                {% for country in countries %}
                    <option value="{{ country.id }}" {% if request.GET.country|default:'' == country.id|stringformat:"s" %}selected{% endif %}>
                        {{ country.name }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <!-- Фильтр по жанрам -->
        <div class="mb-3">
            <label for="genre" class="form-label">Жанр</label>
            <select class="form-select" name="genre" id="genre" onchange="submitFilterForm()">
                <option value="">Все жанры</option>
                {% for genre in genres %}
                    <option value="{{ genre.id }}" {% if request.GET.genre|default:'' == genre.id|stringformat:"s" %}selected{% endif %}>
                        {{ genre.name }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <!-- Фильтр по годам -->
        <div class="mb-3">
            <label for="year" class="form-label">Год</label>
            <select class="form-select" name="year" id="year" onchange="submitFilterForm()">
                <option value="">Все годы</option>
                {% for year in years %}
                    <option value="{{ year }}" {% if request.GET.year == year|stringformat:"s" %}selected{% endif %}>
                        {{ year }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <!-- Сортировка -->
        <div class="mb-3">
            <label for="sort" class="form-label">Сортировка</label>
            <select class="form-select" name="sort" id="sort" onchange="submitFilterForm()">
                <option value="title" {% if request.GET.sort == 'title' %}selected{% endif %}>По названию</option>
                <option value="-average_rating" {% if request.GET.sort == '-average_rating' %}selected{% endif %}>По рейтингу</option>
                <option value="-year" {% if request.GET.sort == '-year' %}selected{% endif %}>По дате выхода</option>
            </select>
        </div>
    </form>
</aside>

movies/src/templates/movies/user_interaction.html
{% if user.is_authenticated %}
<div>

    <form method="POST" action="{% url 'rate_movie' movie.id %}" id="ratingForm">
        {% csrf_token %}
        <label for="ratingSelect" class="form-label me-2">Моя оценка</label>
        <select name="rating" id="ratingSelect" class="form-select w-auto d-inline">
            {% for i in rating_range %}
                <option value="{{ i }}" {% if user_rating == i %}selected{% endif %}>{{ i }}</option>
            {% endfor %}
        </select>
    </form>

    <h5 class="mt-4">Написать рецензию</h5>
    <form method="POST" action="{% url 'review_movie' movie.id %}">
        {% csrf_token %}
        <div class="form-floating">
          <textarea name="review" class="form-control mb-3" placeholder="Leave a review here" id="floatingTextarea2" style="height: 100px" required>{{ user_review.content|default_if_none:'' }}</textarea>
          <label for="floatingTextarea2">Моя рецензия</label>
        </div>

        <button type="submit" class="btn btn-outline-dark">Опубликовать</button>
    </form>
</div>

<script>
    document.getElementById('ratingSelect').addEventListener('change', function () {
        document.getElementById('ratingForm').submit();
    });
</script>

{% endif %}